
# POST http://localhost:3000/v1/auth/register
# Content-Type: application/json

# {
#     "username": "kboy",
#     "phoneNumber": "08179783121",
#     "password": "kboy1234",
#     "email": "quickly2kenny@gmail.com"
# }


# POST http://localhost:3000/v1/auth/forget-password
# Content-Type: application/json

# {
#     "email": "quickly2kenny@gmail.com"
# }

# PUT http://localhost:3000/v1/auth/reset-password
# Content-Type: application/json

# {
#     "OTP": 741923,
#     "reqToken": "U2FsdGVkX1/xcwp00/3XEoeuk0Uu9QM6ror+XJ7cE4QWNayq3Pb4Z9hP5oVfXF9BmptMjEZk2085YI9ekCY9yg==",
#     "newPassword": "every1234"
# }

#  POST http://localhost:3000/v1/auth/login
# Content-Type: application/json

# {
#     "username": "kboy",
#     "password": "kboy1234"
# }

#  POST http://localhost:3000/v1/auth/login
# Content-Type: application/json

# {
#     "username": "kboy",
#     "password": "every1234"
# }
